/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamStudioRouteImport } from './routes/exam-studio'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LessonStudioRouteImport } from './routes/lesson-studio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriRouteImport } from './routes/materi'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as UjianRouteImport } from './routes/ujian'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as OwnerTenantsRouteImport } from './routes/owner_.tenants'
import { Route as OwnerUsersRouteImport } from './routes/owner_.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStudioRoute = ExamStudioRouteImport.update({
  id: '/exam-studio',
  path: '/exam-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonStudioRoute = LessonStudioRouteImport.update({
  id: '/lesson-studio',
  path: '/lesson-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriRoute = MateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianRoute = UjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTenantsRoute = OwnerTenantsRouteImport.update({
  id: '/owner_/tenants',
  path: '/owner/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/owner_/users',
  path: '/owner/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam-studio': typeof ExamStudioRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lesson-studio': typeof LessonStudioRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/media': typeof MediaRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/teacher': typeof TeacherRoute
  '/tenant': typeof TenantRoute
  '/ujian': typeof UjianRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/tenants': typeof OwnerTenantsRoute
  '/owner/users': typeof OwnerUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam-studio': typeof ExamStudioRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lesson-studio': typeof LessonStudioRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/media': typeof MediaRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/teacher': typeof TeacherRoute
  '/tenant': typeof TenantRoute
  '/ujian': typeof UjianRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/tenants': typeof OwnerTenantsRoute
  '/owner/users': typeof OwnerUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam-studio': typeof ExamStudioRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lesson-studio': typeof LessonStudioRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/media': typeof MediaRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/teacher': typeof TeacherRoute
  '/tenant': typeof TenantRoute
  '/ujian': typeof UjianRoute
  '/admin_/users': typeof AdminUsersRoute
  '/owner_/tenants': typeof OwnerTenantsRoute
  '/owner_/users': typeof OwnerUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/exam-studio'
    | '/leaderboard'
    | '/lesson-studio'
    | '/login'
    | '/materi'
    | '/media'
    | '/owner'
    | '/profile'
    | '/teacher'
    | '/tenant'
    | '/ujian'
    | '/admin/users'
    | '/owner/tenants'
    | '/owner/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/exam-studio'
    | '/leaderboard'
    | '/lesson-studio'
    | '/login'
    | '/materi'
    | '/media'
    | '/owner'
    | '/profile'
    | '/teacher'
    | '/tenant'
    | '/ujian'
    | '/admin/users'
    | '/owner/tenants'
    | '/owner/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/exam-studio'
    | '/leaderboard'
    | '/lesson-studio'
    | '/login'
    | '/materi'
    | '/media'
    | '/owner'
    | '/profile'
    | '/teacher'
    | '/tenant'
    | '/ujian'
    | '/admin_/users'
    | '/owner_/tenants'
    | '/owner_/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ExamStudioRoute: typeof ExamStudioRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LessonStudioRoute: typeof LessonStudioRoute
  LoginRoute: typeof LoginRoute
  MateriRoute: typeof MateriRoute
  MediaRoute: typeof MediaRoute
  OwnerRoute: typeof OwnerRoute
  ProfileRoute: typeof ProfileRoute
  TeacherRoute: typeof TeacherRoute
  TenantRoute: typeof TenantRoute
  UjianRoute: typeof UjianRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OwnerTenantsRoute: typeof OwnerTenantsRoute
  OwnerUsersRoute: typeof OwnerUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-studio': {
      id: '/exam-studio'
      path: '/exam-studio'
      fullPath: '/exam-studio'
      preLoaderRoute: typeof ExamStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-studio': {
      id: '/lesson-studio'
      path: '/lesson-studio'
      fullPath: '/lesson-studio'
      preLoaderRoute: typeof LessonStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi': {
      id: '/materi'
      path: '/materi'
      fullPath: '/materi'
      preLoaderRoute: typeof MateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian': {
      id: '/ujian'
      path: '/ujian'
      fullPath: '/ujian'
      preLoaderRoute: typeof UjianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner_/tenants': {
      id: '/owner_/tenants'
      path: '/owner/tenants'
      fullPath: '/owner/tenants'
      preLoaderRoute: typeof OwnerTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner_/users': {
      id: '/owner_/users'
      path: '/owner/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ExamStudioRoute: ExamStudioRoute,
  LeaderboardRoute: LeaderboardRoute,
  LessonStudioRoute: LessonStudioRoute,
  LoginRoute: LoginRoute,
  MateriRoute: MateriRoute,
  MediaRoute: MediaRoute,
  OwnerRoute: OwnerRoute,
  ProfileRoute: ProfileRoute,
  TeacherRoute: TeacherRoute,
  TenantRoute: TenantRoute,
  UjianRoute: UjianRoute,
  AdminUsersRoute: AdminUsersRoute,
  OwnerTenantsRoute: OwnerTenantsRoute,
  OwnerUsersRoute: OwnerUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
